name: Build BitWardens
on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
    - name: Checkout repo
      uses: actions/checkout@master
        
    - run: |
        cd ~
        git clone https://github.com/bitwarden/browser.git
        npm install --global gulp-cli
        cd browser
        echo "==============="
        pwd
        echo "==============="
        npm install
        cp -rv $GITHUB_WORKSPACE/icons-hypha/* src/images/
        npm run build
        npm run dist:firefox
        ls -la ~/browser
        echo "==============="
        ls -la ~/browser/dist/
        echo "==============="
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          ~/browser/dist/dist-firefox.zip
