name: Build BitWardens
on:
  push:

env:
  JWTISSUER: ${{ secrets.JWTISSUER }}
  JWTSECRET: ${{ secrets.JWTSECRET }}

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]
    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}


      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your workflow can access it
    - name: Checkout repo
      uses: actions/checkout@master
        
    - run: |
        git clone https://github.com/bitwarden/browser.git
        npm install --global gulp-cli
        npm install --global web-ext
        cd browser
        npm install
        cd apps/browser
        cp -rv $GITHUB_WORKSPACE/icons-hypha/* src/images/
        npm run build
        npm run dist:firefox
        mkdir $GITHUB_WORKSPACE/release
        cd dist
        unzip dist-firefox.zip
        ls
        echo "=========== $JWTSECRET ==============="
        echo "=========================="
        export
        echo "=========================="
        web-ext sign --api-key="$JWTISSUER" --api-secret="$JWTSECRET"
        
        ls
        cp dist/dist-firefox.zip $GITHUB_WORKSPACE/release
        cd $GITHUB_WORKSPACE
        ls release
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          release/*.zip
